# Generated by Django 3.2.6 on 2024-10-31 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='doc.subtopic'),
        ),
    ]
