# Generated by Django 3.2.6 on 2024-11-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0012_auto_20241113_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
