# Generated by Django 5.1.3 on 2024-12-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0013_alter_category_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'created_at', 'name']},
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['order', 'created_at', 'title']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'created_at', 'title']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order', 'created_at', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['order', 'created_at', 'name']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'created_at', 'name']},
        ),
    ]
