# Generated by Django 5.1.3 on 2024-12-13 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0014_alter_category_options_alter_instruction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_viewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='instruction',
            name='last_viewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='section',
            name='last_viewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='last_viewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='last_viewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_viewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
